// apps/web/src/components/AppIcon.tsx
// Centralized icon system. All icons go through this component.
// Uses @fluentui/react-icons only. No Font Awesome, no inline SVG.

import {
  SearchRegular,
  SearchFilled,
  AddRegular,
  AddFilled,
  EditRegular,
  EditFilled,
  DeleteRegular,
  DeleteFilled,
  LockClosedRegular,
  LockClosedFilled,
  LockOpenRegular,
  LockOpenFilled,
  ShieldRegular,
  ShieldFilled,
  ShieldCheckmarkRegular,
  ShieldCheckmarkFilled,
  PeopleRegular,
  PeopleFilled,
  PersonRegular,
  PersonFilled,
  PersonCircleRegular,
  PersonCircleFilled,
  PersonAddRegular,
  PersonAddFilled,
  WarningRegular,
  WarningFilled,
  CheckmarkCircleRegular,
  CheckmarkCircleFilled,
  SettingsRegular,
  SettingsFilled,
  ArrowRightRegular,
  ArrowRightFilled,
  ArrowLeftRegular,
  ArrowLeftFilled,
  GlobeRegular,
  GlobeFilled,
  DatabaseRegular,
  DatabaseFilled,
  CalendarRegular,
  CalendarFilled,
  ClockRegular,
  ClockFilled,
  DesktopRegular,
  DesktopFilled,
  KeyRegular,
  KeyFilled,
  RocketRegular,
  RocketFilled,
  DataTrendingRegular,
  DataTrendingFilled,
  DocumentRegular,
  DocumentFilled,
  TicketDiagonalRegular,
  TicketDiagonalFilled,
  BotRegular,
  BotFilled,
  ScalesRegular,
  ScalesFilled,
  WrenchRegular,
  WrenchFilled,
  OpenRegular,
  OpenFilled,
  DismissRegular,
  DismissFilled,
  DismissCircleRegular,
  DismissCircleFilled,
  AlertRegular,
  AlertFilled,
  SignOutRegular,
  SignOutFilled,
  AppsRegular,
  AppsFilled,
  PersonStarRegular,
  PersonStarFilled,
  PersonArrowRightRegular,
  PersonArrowRightFilled,
  ClipboardTaskList16Regular,
  ClipboardTaskList16Filled,
  ChevronDownRegular,
  ChevronDownFilled,
  HeadsetRegular,
  HeadsetFilled,
  PeopleTeamRegular,
  PeopleTeamFilled,
  StarRegular,
  StarFilled,
  BookRegular,
  BookFilled,
  CodeRegular,
  CodeFilled,
  GridRegular,
  GridFilled,
  HatGraduationRegular,
  HatGraduationFilled,
  ClipboardBulletListLtrRegular,
  ClipboardBulletListLtrFilled,
  DataBarVerticalRegular,
  DataBarVerticalFilled,
  CubeRegular,
  CubeFilled,
  MoneyRegular,
  MoneyFilled,
  CartRegular,
  CartFilled,
  MegaphoneRegular,
  MegaphoneFilled,
  FlashRegular,
  FlashFilled,
  ShieldTaskRegular,
  ShieldTaskFilled,
  NavigationRegular,
  NavigationFilled,
} from '@fluentui/react-icons';

const iconMapRegular: Record<string, React.ComponentType<{ className?: string }>> = {
  search: SearchRegular,
  add: AddRegular,
  edit: EditRegular,
  delete: DeleteRegular,
  lock: LockClosedRegular,
  unlock: LockOpenRegular,
  shield: ShieldRegular,
  shieldCheck: ShieldCheckmarkRegular,
  shieldTask: ShieldTaskRegular,
  users: PeopleRegular,
  person: PersonRegular,
  personCircle: PersonCircleRegular,
  personAdd: PersonAddRegular,
  warning: WarningRegular,
  success: CheckmarkCircleRegular,
  settings: SettingsRegular,
  arrowRight: ArrowRightRegular,
  arrowLeft: ArrowLeftRegular,
  globe: GlobeRegular,
  database: DatabaseRegular,
  calendar: CalendarRegular,
  clock: ClockRegular,
  desktop: DesktopRegular,
  key: KeyRegular,
  rocket: RocketRegular,
  chart: DataTrendingRegular,
  document: DocumentRegular,
  ticket: TicketDiagonalRegular,
  bot: BotRegular,
  scale: ScalesRegular,
  wrench: WrenchRegular,
  external: OpenRegular,
  dismiss: DismissRegular,
  dismissCircle: DismissCircleRegular,
  alert: AlertRegular,
  signOut: SignOutRegular,
  apps: AppsRegular,
  personStar: PersonStarRegular,
  personArrowRight: PersonArrowRightRegular,
  clipboardTaskList: ClipboardTaskList16Regular,
  chevronDown: ChevronDownRegular,
  headset: HeadsetRegular,
  flow: DataTrendingRegular,
  peopleTeam: PeopleTeamRegular,
  star: StarRegular,
  book: BookRegular,
  code: CodeRegular,
  grid: GridRegular,
  hatGraduation: HatGraduationRegular,
  clipboardBulletList: ClipboardBulletListLtrRegular,
  dataBarVertical: DataBarVerticalRegular,
  cube: CubeRegular,
  money: MoneyRegular,
  cart: CartRegular,
  megaphone: MegaphoneRegular,
  flash: FlashRegular,
  navigation: NavigationRegular,
};

const iconMapFilled: Record<string, React.ComponentType<{ className?: string }>> = {
  search: SearchFilled,
  add: AddFilled,
  edit: EditFilled,
  delete: DeleteFilled,
  lock: LockClosedFilled,
  unlock: LockOpenFilled,
  shield: ShieldFilled,
  shieldCheck: ShieldCheckmarkFilled,
  shieldTask: ShieldTaskFilled,
  users: PeopleFilled,
  person: PersonFilled,
  personCircle: PersonCircleFilled,
  personAdd: PersonAddFilled,
  warning: WarningFilled,
  success: CheckmarkCircleFilled,
  settings: SettingsFilled,
  arrowRight: ArrowRightFilled,
  arrowLeft: ArrowLeftFilled,
  globe: GlobeFilled,
  database: DatabaseFilled,
  calendar: CalendarFilled,
  clock: ClockFilled,
  desktop: DesktopFilled,
  key: KeyFilled,
  rocket: RocketFilled,
  chart: DataTrendingFilled,
  document: DocumentFilled,
  ticket: TicketDiagonalFilled,
  bot: BotFilled,
  scale: ScalesFilled,
  wrench: WrenchFilled,
  external: OpenFilled,
  dismiss: DismissFilled,
  dismissCircle: DismissCircleFilled,
  alert: AlertFilled,
  signOut: SignOutFilled,
  apps: AppsFilled,
  personStar: PersonStarFilled,
  personArrowRight: PersonArrowRightFilled,
  clipboardTaskList: ClipboardTaskList16Filled,
  chevronDown: ChevronDownFilled,
  headset: HeadsetFilled,
  flow: DataTrendingFilled,
  peopleTeam: PeopleTeamFilled,
  star: StarFilled,
  book: BookFilled,
  code: CodeFilled,
  grid: GridFilled,
  hatGraduation: HatGraduationFilled,
  clipboardBulletList: ClipboardBulletListLtrFilled,
  dataBarVertical: DataBarVerticalFilled,
  cube: CubeFilled,
  money: MoneyFilled,
  cart: CartFilled,
  megaphone: MegaphoneFilled,
  flash: FlashFilled,
  navigation: NavigationFilled,
};

export type IconName = keyof typeof iconMapRegular;

export interface AppIconProps {
  name: IconName;
  size?: number;
  filled?: boolean;
  className?: string;
}

export function AppIcon({ name, size = 20, filled = false, className }: AppIconProps) {
  const IconComponent = filled && iconMapFilled[name] ? iconMapFilled[name] : iconMapRegular[name];
  if (!IconComponent) return null;
  return (
    <span
      className={className}
      style={{ display: 'inline-flex', fontSize: size, width: size, height: size }}
      aria-hidden
    >
      <IconComponent />
    </span>
  );
}
