version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecc-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  ecc-api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: ecc-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SecurityDb=Server=sqlserver,1433;Database=ECC_SecurityDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"

volumes:
  sql_data:
