namespace Kernel.Infrastructure.Persistence.Models;

// ============================================================
// AI-GENERATED CODE — DO NOT MODIFY WITHOUT PROMPT RE-EXECUTION
// FEAT-ID:    FEAT-NNN
// TASK-ID:    T-NNN
// PROMPT-ID:  PR-NNN-infrastructure-persistence-audit-log-entry
// Generated:  2026-03-26 | ChatGPT REVIEW: PENDING
// ============================================================

/// <summary>
/// Persistence model representing a single audit log record written to the <c>audit_action_logs</c> table.
/// This model lives in Infrastructure because it is a persistence concern, not a domain concept.
/// </summary>
public sealed class AuditLogEntry
{
    /// <summary>Surrogate primary key (auto-generated by the database).</summary>
    public int AuditActionPid { get; set; }

    /// <summary>Foreign key to audit_sessions table. Required by DB schema.</summary>
    public int AuditSessionPid { get; set; }

    /// <summary>Foreign key to security_users table — the actor performing the action.</summary>
    public int SecurityUserPid { get; set; }

    /// <summary>UTC timestamp when the action occurred.</summary>
    public DateTime ActionTimestamp { get; set; }

    /// <summary>Type of action, e.g. "CREATE", "UPDATE", "DELETE".</summary>
    public string? ActionType { get; set; }

    /// <summary>Human-readable action name.</summary>
    public string? ActionName { get; set; }

    /// <summary>The type of entity affected, e.g. "SecurityUser".</summary>
    public string? EntityType { get; set; }

    /// <summary>Integer identifier of the affected entity.</summary>
    public int? EntityPid { get; set; }

    /// <summary>JSON snapshot of the entity state before the change.</summary>
    public string? OldValue { get; set; }

    /// <summary>JSON snapshot of the entity state after the change.</summary>
    public string? NewValue { get; set; }

    /// <summary>Created timestamp (required by DB schema).</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>Identifier of the process/service that created this record (required by DB schema).</summary>
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>Soft-delete flag (required by DB schema, always false for audit logs).</summary>
    public bool DeletedFlag { get; set; }
}
