name: CI Frontend

on:
  push:
    paths:
      - 'apps/frontend/**'
  pull_request:
    paths:
      - 'apps/frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        working-directory: apps/frontend
        run: npm ci
      - name: Build
        working-directory: apps/frontend
        run: npm run build
